# Generated by Django 3.0.3 on 2020-02-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njrealestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='acreage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='additionallots',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='assessed1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='assessed2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='assessed3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='assessed4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='bankcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='block',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='buildingassmnt1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='buildingassmnt2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='buildingassmnt3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='buildingassmnt4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='buildingclass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='buildingdesc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='classcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='deedbook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='deedpage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='epldesc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='eplfacilityname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='eplfurther',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='eplinit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='eplown',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='eplstatute',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='epluse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='exempt1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='exempt2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='exempt3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='exempt4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='landassmnt1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='landassmnt2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='landassmnt3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='landassmnt4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='landdesc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='lot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='mappage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='mortgageaccount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='municipality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='neigh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='nucode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner1citystatezip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner2citystatezip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner3citystatezip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owner4citystatezip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='owneraddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='ownercitystatezip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='ownername',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='priorblock',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='priorlot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='priorqual',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='propertyclass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='propertylocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='qual',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='ratio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='saledate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='saleprice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sptaxcred1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sptaxcred2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sptaxcred3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sptaxcred4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sqft',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='street1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='street2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='street3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='street4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='stydesc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='style',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='taxes1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='taxes2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='taxes3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='taxes4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='totalassmnt1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='totalassmnt2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='totalassmnt3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='totalassmnt4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='typeuse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='updated',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='vcs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='year1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='year2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='year3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='year4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='yrbuilt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='zone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
