# Generated by Django 3.0.3 on 2020-02-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njrealestate', '0002_auto_20200227_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('muncicpality', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
            ],
        ),
    ]
