# Generated by Django 3.0.3 on 2020-02-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('njrealestate', '0003_municipalities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipalities',
            old_name='muncicpality',
            new_name='municipality',
        ),
    ]
