# Generated by Django 3.0.3 on 2020-02-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njrealestate', '0005_propertyclassifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualificationcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
