# Generated by Django 3.0.3 on 2020-03-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('OBJECTID', models.IntegerField(primary_key=True, serialize=False)),
                ('SSL', models.CharField(max_length=255, null=True)),
                ('ASSESSOR_NAME', models.CharField(max_length=255, null=True)),
                ('LAND_USE_CODE', models.CharField(max_length=255, null=True)),
                ('LANDAREA', models.CharField(max_length=255, null=True)),
                ('PROPERTY_ADDRESS', models.CharField(max_length=255, null=True)),
                ('OTR_NEIGHBORHOOD_CODE', models.CharField(max_length=255, null=True)),
                ('OWNER_NAME_PRIMARY', models.CharField(max_length=255, null=True)),
                ('CAREOF_NAME', models.CharField(max_length=255, null=True)),
                ('OWNER_ADDRESS_LINE1', models.CharField(max_length=255, null=True)),
                ('OWNER_ADDRESS_LINE2', models.CharField(max_length=255, null=True)),
                ('OWNER_ADDRESS_CITYSTZIP', models.CharField(max_length=255, null=True)),
                ('VACANT_USE', models.CharField(max_length=255, null=True)),
                ('HOMESTEAD_DESCRIPTION', models.CharField(max_length=255, null=True)),
                ('TAX_TYPE_DESCRIPTION', models.CharField(max_length=255, null=True)),
                ('MIXED_USE', models.CharField(max_length=255, null=True)),
                ('OWNER_OCCUPIED_COOP_UNITS', models.CharField(max_length=255, null=True)),
                ('DEED_DATE', models.CharField(max_length=255, null=True)),
                ('CURRENT_ASSESSMENT_CAP', models.CharField(max_length=255, null=True)),
                ('PROPOSED_ASSESSMENT_CAP', models.CharField(max_length=255, null=True)),
                ('OWNER_NAME_SECONDARY', models.CharField(max_length=255, null=True)),
                ('ADDRESS_ID', models.TextField(null=True)),
                ('LASTMODIFIEDDATE', models.CharField(max_length=255, null=True)),
                ('APPRAISED_VALUE_PRIOR_LAND', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_PRIOR_IMPR', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_PRIOR_TOTAL', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_CURRENT_LAND', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_CURRENT_TOTAL', models.IntegerField(null=True)),
                ('TAXRATE', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('LAST_SALE_PRICE', models.IntegerField(null=True)),
                ('LAST_SALE_DATE', models.CharField(max_length=30, null=True)),
                ('APPRAISED_VALUE_PROPOSED_LAND', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_PROPOSED_IMPR', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_PROPOSED_TOTAL', models.IntegerField(null=True)),
                ('APPRAISED_VALUE_CURRENT_BLDG', models.IntegerField(null=True)),
            ],
        ),
    ]
