# Generated by Django 3.0.3 on 2020-03-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcrealestate', '0002_landuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landuse',
            name='id',
        ),
        migrations.AlterField(
            model_name='landuse',
            name='LAND_USE_CODE',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
